on:
  push:

jobs:
  ci:
    name: "CI"
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-go@v3
      with:
        cache: true
        go-version-file: go.mod

    - uses: actions/cache@v3
      with:
        path: gravel/cache.json.gz
        key: ${{ github.ref_name }}-${{ github.event.after }}
        restore-keys: |
          ${{ github.ref_name }}-${{ github.event.before }}
          main-${{ github.event.before }}

    - name: Print build plan
      run: go run ./cmd/gravel plan

    - name: Run build
      run: go run ./cmd/gravel build
    
    - name: Set up Ko
      uses: ko-build/setup-ko@v0.6
    
    - name: Build container
      run: ko build --base-import-paths ./cmd/gravel
    
