on:
  push:

jobs:
  ci:
    name: "CI"
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-go@v3
      with:
        go-version-file: go.mod
    
    - run: go run ./cmd/gravel build --no-cache
